{
 "title": "Copilotの利用状況",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "提案行数(日別)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_code_suggestions) by (date)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "承認行数(日別)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(date) (total_code_acceptances)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "提案承認率(日別)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(total_code_acceptances) by (date) / sum(total_code_suggestions) by (date) * 100) by (date)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "累計利用人数(日別)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_active_users) by (date)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}